[package]
name = "math_9375"
version = "0.1.0"
authors = ["chin0 <raspy1108@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
